-- ============================================================
-- CRM + Controle de Obras — Esquema inicial Supabase (v1)
-- Mapeado a partir do db.* (localStorage) do crm.html em 15/06/2026
-- Execute este script no SQL Editor do Supabase (projeto novo)
-- ============================================================

-- Usamos "generated by default as identity" (em vez de "always")
-- para permitir inserir ids explícitos no seed abaixo, mantendo
-- compatibilidade com os ids já usados no localStorage.

-- ---------- EMPRESA (linha única com os dados da empresa) ----------
create table empresa (
  id bigint generated by default as identity primary key,
  razao text default '',
  fantasia text default '',
  cnpj text default '',
  ie text default '',
  tel text default '',
  email text default '',
  site text default '',
  logo text default '',
  endereco jsonb default '{}'::jsonb
);

-- ---------- FASES DO CRM (kanban do Painel) ----------
create table fases_crm (
  id bigint generated by default as identity primary key,
  nome text not null,
  cor text not null,
  ordem int not null,
  tipo text  -- 'perdido' | 'concluido' | null
);

-- ---------- FASES DA PROPOSTA ----------
create table fases_proposta (
  id bigint generated by default as identity primary key,
  nome text not null,
  cor text not null,
  ordem int not null,
  tipo text  -- 'aprovada' | 'perdida' | null
);

-- ---------- ORIGEM DO LEAD ----------
create table origens (
  id bigint generated by default as identity primary key,
  nome text not null
);

-- ---------- FUNÇÕES NA EMPRESA ----------
create table funcoes (
  id bigint generated by default as identity primary key,
  nome text not null
);

-- ---------- GRUPOS DE ACESSO (RBAC) ----------
create table grupos (
  id bigint generated by default as identity primary key,
  nome text not null,
  admin boolean not null default false,
  telas text[] not null default '{}',
  recursos text[] not null default '{}'
);

-- ---------- USUÁRIOS (vinculados ao Supabase Auth) ----------
create table usuarios (
  id bigint generated by default as identity primary key,
  auth_id uuid unique references auth.users(id) on delete set null,
  nome text not null,
  login text unique not null,
  funcao text,
  grupo_id bigint references grupos(id),
  dias_logado int default 30,
  ativo boolean default true
);

-- ---------- CLIENTES ----------
create table clientes (
  id bigint generated by default as identity primary key,
  nome text not null,
  tel text,
  email text,
  cidade text,
  endereco jsonb default '{}'::jsonb
);

-- ---------- OBRAS (1 cliente : N obras) ----------
create table obras (
  id bigint generated by default as identity primary key,
  cliente_id bigint references clientes(id) on delete cascade,
  nome text not null,
  endereco jsonb default '{}'::jsonb
);

-- ---------- CARDS (cartões do CRM) ----------
create table cards (
  id bigint generated by default as identity primary key,
  num int not null,
  cliente_id bigint references clientes(id),
  obra_id bigint references obras(id),
  origem_id bigint references origens(id),
  fase_id bigint references fases_crm(id),
  responsavel text,
  agenda timestamptz,
  valor numeric(14,2) default 0,
  perdido boolean default false,
  concluido boolean default false,
  created_at timestamptz default now()
);
create index idx_cards_cliente on cards(cliente_id);
create index idx_cards_fase on cards(fase_id);
create index idx_cards_obra on cards(obra_id);

-- ---------- HISTÓRICO DE CONTATOS DO CARD ----------
create table card_historico (
  id bigint generated by default as identity primary key,
  card_id bigint references cards(id) on delete cascade,
  data timestamptz,
  texto text not null
);
create index idx_historico_card on card_historico(card_id);

-- ---------- PROPOSTAS ----------
create table propostas (
  id bigint generated by default as identity primary key,
  numero text unique not null,
  card_id bigint references cards(id) on delete cascade,
  cliente_id bigint references clientes(id),
  obra_id bigint references obras(id),
  data_emissao date,
  valor numeric(14,2) default 0,
  validade_dias int default 10,
  fase_id bigint references fases_proposta(id),
  status text not null default 'emitida', -- 'emitida' | 'aprovada'
  aditivo boolean default false,
  data_aprovacao date,
  fase_anterior bigint
);
create index idx_propostas_card on propostas(card_id);

-- ---------- ITENS DA PROPOSTA APROVADA (vindos do Excel) ----------
create table proposta_itens (
  id bigint generated by default as identity primary key,
  proposta_id bigint references propostas(id) on delete cascade,
  item text,
  descricao text,
  qtd numeric,
  unit numeric(14,2),
  total numeric(14,2),
  tipo text,
  categoria text -- 'servico' | 'produto'
);
create index idx_itens_proposta on proposta_itens(proposta_id);

-- ---------- ARQUIVOS DA PROPOSTA (metadados; arquivo no Storage) ----------
create table proposta_arquivos (
  id text primary key,
  proposta_id bigint references propostas(id) on delete cascade,
  nome text not null,
  storage_path text not null
);

-- ============================================================
-- ROW LEVEL SECURITY
-- v1: qualquer usuário autenticado (login pelo Supabase Auth)
-- tem acesso total. As regras finas de RBAC (grupos/telas/
-- recursos) continuam controladas pela aplicação, como hoje.
-- Pode ser refinado depois sem mexer na estrutura das tabelas.
-- ============================================================
do $$
declare t text;
begin
  for t in select unnest(array[
    'empresa','fases_crm','fases_proposta','origens','funcoes','grupos',
    'usuarios','clientes','obras','cards','card_historico',
    'propostas','proposta_itens','proposta_arquivos'
  ])
  loop
    execute format('alter table %I enable row level security', t);
    execute format(
      'create policy "authenticated_full_access" on %I for all to authenticated using (true) with check (true)',
      t
    );
  end loop;
end $$;

-- ============================================================
-- BUCKET DE STORAGE PARA OS ARQUIVOS DAS PROPOSTAS (PDF/Excel)
-- ============================================================
insert into storage.buckets (id, name, public)
values ('propostas', 'propostas', false)
on conflict (id) do nothing;

create policy "authenticated_storage_propostas"
on storage.objects for all to authenticated
using (bucket_id = 'propostas')
with check (bucket_id = 'propostas');

-- ============================================================
-- SEED — mesmas fases/origens/funções/grupos do SEED do crm.html
-- (clientes, cards e propostas reais ficam para a migração de
-- dados, numa etapa futura)
-- ============================================================

insert into empresa (id, razao, fantasia) values (1, '', '') ;

insert into fases_crm (id, nome, cor, ordem, tipo) values
 (1,  'Contato Frio',            '#607d8b', 1,  null),
 (2,  'Apresentação',            '#2191b0', 2,  null),
 (3,  'Orçamento',                '#4db6ac', 3,  null),
 (4,  'Negociação',               '#f4866d', 4,  null),
 (5,  'Pós-Venda',                '#1d8348', 5,  null),
 (6,  'Chamado',                  '#ffee33', 6,  null),
 (7,  'Perdido/Abandonado',       '#ff2d00', 7,  'perdido'),
 (9,  'Aguardando Obra Avançar',  '#ddd0f5', 9,  null),
 (10, 'Obra Concluída',           '#00bfff', 10, null),
 (11, 'Instalação',               '#1c8dbf', 11, null),
 (12, 'Criando Projeto',          '#7cb342', 12, null),
 (13, 'CRM Concluído',            '#6a1b9a', 13, 'concluido');

insert into fases_proposta (id, nome, cor, ordem, tipo) values
 (1, 'Em Elaboração',      '#90a4ae', 1, null),
 (2, 'Enviada ao Cliente',  '#1c8dbf', 2, null),
 (3, 'Em Negociação',       '#fd7e14', 3, null),
 (4, 'Revisão Solicitada',  '#ffc107', 4, null),
 (5, 'Aprovada',            '#6a1b9a', 5, 'aprovada'),
 (6, 'Perdida/Abandonada',  '#ff2d00', 6, 'perdida');

insert into origens (id, nome) values
 (1, 'JÁ É CLIENTE'),
 (2, 'Arquiteto'),
 (3, 'Empreiteiro'),
 (4, 'Vendedor'),
 (5, 'Google'),
 (6, 'Midias Sociais'),
 (7, 'Fornecedor'),
 (8, 'Indicação Cliente'),
 (9, 'Amigo'),
 (10, 'Engenheiro');

insert into funcoes (id, nome) values
 (1, 'Técnico'),
 (2, 'Projetista'),
 (3, 'Vendedor'),
 (4, 'Administrativo'),
 (5, 'Sócio');

insert into grupos (id, nome, admin, telas, recursos) values
 (1, 'Administradores', true,  '{}', array['aba-propostas','aba-obras']),
 (2, 'Equipe',          false, array['painel','clientes'], array['aba-propostas','aba-obras']);

-- Ajusta as sequences depois dos ids explícitos acima
select setval(pg_get_serial_sequence('fases_crm','id'), (select max(id) from fases_crm));
select setval(pg_get_serial_sequence('fases_proposta','id'), (select max(id) from fases_proposta));
select setval(pg_get_serial_sequence('origens','id'), (select max(id) from origens));
select setval(pg_get_serial_sequence('funcoes','id'), (select max(id) from funcoes));
select setval(pg_get_serial_sequence('grupos','id'), (select max(id) from grupos));
select setval(pg_get_serial_sequence('empresa','id'), (select max(id) from empresa));

-- ============================================================
-- PRÓXIMO PASSO MANUAL (não dá pra fazer via SQL):
-- 1. Em Authentication > Users, crie o usuário admin (e-mail/senha).
-- 2. Copie o "User UID" gerado e rode:
--
--    insert into usuarios (auth_id, nome, login, funcao, grupo_id, dias_logado, ativo)
--    values ('COLE-O-UID-AQUI', 'Cleverson', 'cleverson', 'Sócio', 1, 30, true);
--
-- ============================================================
