-- ============================================================
-- CRM + Controle de Obras — Migração: Logs de Auditoria
-- Execute no SQL Editor do Supabase após o schema.sql inicial
-- ============================================================

-- Retenção de logs (dias) na tabela empresa
alter table empresa add column if not exists log_retencao_dias int default 90;

-- Tabela de logs de auditoria
create table if not exists audit_logs (
  id        bigint generated by default as identity primary key,
  user_id   bigint references usuarios(id) on delete set null,
  user_nome text not null,
  acao      text not null,           -- 'criar' | 'editar' | 'excluir' | 'login' | 'logout' | 'aprovar' | 'reverter' | etc.
  entidade  text not null,           -- 'cliente' | 'obra' | 'card' | 'proposta' | 'fase_crm' | 'fase_proposta' | 'origem' | 'funcao' | 'grupo' | 'usuario' | 'config' | 'sistema'
  entidade_id text,                  -- id do registro afetado (pode ser nulo para ações de sistema)
  descricao text not null,           -- descrição legível do que foi feito
  created_at timestamptz default now()
);

create index if not exists idx_audit_logs_user on audit_logs(user_id);
create index if not exists idx_audit_logs_created on audit_logs(created_at desc);
create index if not exists idx_audit_logs_entidade on audit_logs(entidade);

-- RLS
alter table audit_logs enable row level security;
create policy "authenticated_full_access" on audit_logs for all to authenticated using (true) with check (true);
